language: go
sudo: required
go:
  - 1.10.x
  - master
services:
  - docker
addons:
  apt:
    update: true
before_install:
  - docker-compose up -d
  - sleep 20s
script:
  - make ci
after_script:
  - make cover
