language: go
sudo: required
go:
  - 1.10.x
  - master
services:
  - docker
addons:
  apt:
    update: true
before_install:
  - sudo apt-get install libpcap-dev
  - docker-compose up -d postgres mysql57
  - sleep 20s
script:
  - make ci
after_script:
  - make cover
