language: go
sudo: required
go:
  - 1.11
  - master
matrix:
  allow_failures:
    - go: master
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - docker-ce
      - libpcap-dev
      - netcat
before_install:
  - sudo pip install codecov
  - docker --version
  - docker-compose --version
  - docker-compose up -d postgres mysql57 proxy-protocol-proxy-linux proxy-protocol-mariadb
  - while ! nc -w 1 127.0.0.1 33066 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
  - while ! nc -w 1 127.0.0.1 54322 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
script:
  - make ci
after_script:
  - codecov
cache:
  directories:
    - /go/pkg/mod/cache/download
    - /go/src/github.com
