version: '3.4'

services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql57:
    image: mysql:5.7
    restart: always
    ports:
      - "33066:3306"
    volumes:
      - ./test/mysql.conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
