version: '3.4'

services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql57:
    image: mysql:5.7
    restart: always
    ports:
      - "33066:3306"
    volumes:
      - ./testdata/mysql.conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  proxy-protocol-proxy-mac:
    image: nginx
    restart: always
    ports:
      - "33068:33068"
      - "33069:33069"
    volumes:
      - ./testdata/nginx/nginx.conf:/etc/nginx/nginx.conf
  proxy-protocol-proxy-linux:
    image: nginx
    restart: always
    network_mode: host
    volumes:
      - ./testdata/nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    expose:
      - "33068"
      - "33069"
  proxy-protocol-mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - "33071:3306"
    volumes:
      - ./testdata/mariadb.conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos7
      args:
        GO_VERSION: 1.11
        LIBPCAP_VERSION: 1.9.0
    volumes:
      - $GOPATH:/go
    environment:
      DIST: el7
    command: make depsdev build_in_docker build_static_in_docker build_rpm
  centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos6
      args:
        GO_VERSION: 1.11
        LIBPCAP_VERSION: 1.9.0
    volumes:
      - $GOPATH:/go
    environment:
      DIST: el6
    command: make depsdev build_in_docker build_static_in_docker build_rpm
  ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu16
      args:
        GO_VERSION: 1.11
        LIBPCAP_VERSION: 1.9.0
    volumes:
      - $GOPATH:/go
    environment:
      DIST: xenial
    command: make depsdev build_in_docker build_static_in_docker build_deb
