version: '3.4'

services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql57:
    image: mysql:5.7
    restart: always
    ports:
      - "33066:3306"
    volumes:
      - ./testdata/mysql.conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  proxy-protocol-proxy-mac:
    image: mminks/haproxy-docker-logging
    restart: always
    ports:
      - "33068:33068"
      - "33069:33069"
      - "33070:33070"
      - "33071:33071"
    volumes:
      - ./testdata/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  proxy-protocol-proxy-linux:
    image: mminks/haproxy-docker-logging
    restart: always
    network_mode: host
    volumes:
      - ./testdata/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    expose:
      - "33068"
      - "33069"
      - "33070"
      - "33071"
  proxy-protocol-mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - "33081:3306"
    volumes:
      - ./testdata/mariadb.conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
