name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev netcat

      - name: Run Docker containers
        run: |
          docker --version
          docker-compose --version
          docker-compose up -d postgres mysql57 proxy-protocol-proxy-linux proxy-protocol-mariadb
          while ! nc -w 1 127.0.0.1 33066 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
          while ! nc -w 1 127.0.0.1 54322 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
          while ! nc -w 1 127.0.0.1 33081 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
          while ! nc -w 1 127.0.0.1 33068 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
          while ! nc -w 1 127.0.0.1 33069 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
          while ! nc -w 1 127.0.0.1 33070 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
          while ! nc -w 1 127.0.0.1 33071 > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;

      - name: Test
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
