name: tagpr
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: k1LoW/run-on-container@main
        with:
          run: |
            ls -la
            apt-get -qq update
            apt-get install -qq git
            git status
          image: ubuntu:latest
          platform: linux/amd64
