name: test
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: k1LoW/run-on-container@main
        with:
          run: |
            yum remove git*
            yum -y install epel-release centos-release-scl
            yum -y groupinstall "Development Tools"
            yum -y install wget perl-CPAN gettext-devel perl-devel openssl-devel zlib-devel curl curl-devel expat-devel getopt asciidoc xmlto docbook2X devtoolset-10
            ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
            export GIT_VER="v2.44.0"
            wget https://github.com/git/git/archive/${GIT_VER}.tar.gz
            tar -xvf ${GIT_VER}.tar.gz
            rm -f ${GIT_VER}.tar.gz
            cd git-*
            scl enable devtoolset-10 'make configure && ./configure --prefix=/usr && make && make install'

            git config --global --add safe.directory $WORKSPACE
          image: centos:7
          platform: linux/arm64
          shell: bash
